abstract: add guid query for DoCoMo imode
author: Kazuhiro Osawa <ko@yappo.ne.jp>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: HTML-StickyQuery-DoCoMoGUID
no_index: 
  directory: 
    - inc
    - t
requires: 
  HTML::StickyQuery: 0
version: 0.01
