---
abstract: 'add guid query for DoCoMo imode'
author:
  - 'Kazuhiro Osawa <yappo {at} shibuya [dot] pl>,'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-StickyQuery-DoCoMoGUID
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Filter::Util::Call: 0
  HTML::StickyQuery: 0.13
resources:
  homepage: http://github.com/yappo/p5-HTML-StickyQuery-DoCoMoGUID/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/yappo/p5-HTML-StickyQuery-DoCoMoGUID.git
version: 0.03
